const fs=require('fs');
let lines=fs.readFileSync('src/components/forms/CustomerMeasurementForm.tsx','utf8').split('\n');
lines[157]="      toast.success(isUrdu ? 'ناپ صاف کر دیے گئے' : 'Measurements cleared successfully');";
lines[207]="              {isUrdu ? 'شلوار قمیض' : 'Shalwar Kameez'}";
lines[213]="              {isUrdu ? 'واسکٹ' : 'Waistcoat'}";
lines[219]="              {isUrdu ? 'کوٹ' : 'Coat'}";
lines[224]="            {isUrdu ? 'ناپ پرچی' : 'Measurement Slip'}";
lines[227]="              <Save className=\"w-3 h-3\" /> {isUrdu ? 'محفوظ ہو رہا ہے...' : 'Saving...'}";
lines[232]="              <CheckCircle className=\"w-3 h-3\" /> {isUrdu ? 'محفوظ' : 'Saved'}";
lines[237]="              <AlertCircle className=\"w-3 h-3\" /> {isUrdu ? 'خرابی' : 'Error'}";
lines[248]="                {isUrdu ? 'ری سیٹ' : 'Reset'}";
lines[254]="                title={isUrdu ? 'پری ویو' : 'Preview'}";
lines[257]="                  {isUrdu ? 'پری ویو' : 'Preview'}";
lines[265]="                  {isUrdu ? 'پرنٹ' : 'Print'}";
lines[480]="                          <option value=\"\" disabled>منتخب کریں</option>";
lines[585]="                          <span className=\"text-[13px] font-semibold text-slate-700 font-urdu leading-[2.2]\" style={{ fontFamily: \"'NotoNastaliqUrdu', serif\" }} dir=\"rtl\">ڈبل پریس</span>";
lines[640]="                        <span className=\"text-[13px] font-semibold text-slate-700 font-urdu leading-[2.2] whitespace-nowrap\" style={{ fontFamily: \"'NotoNastaliqUrdu', serif\" }} dir=\"rtl\">بین کالر</span>";
lines[644]="                        <span className=\"text-[13px] font-semibold text-slate-700 font-urdu leading-[2.2] whitespace-nowrap\" style={{ fontFamily: \"'NotoNastaliqUrdu', serif\" }} dir=\"rtl\">سادہ کالر</span>";
lines[660]="                        <span className=\"text-[13px] font-semibold text-slate-700 font-urdu leading-[2.2]\" style={{ fontFamily: \"'NotoNastaliqUrdu', serif\" }} dir=\"rtl\">پٹی کاج ہو</span>";
lines[675]="                    رسید گم ہو جانے پر اگر عدد میں کسی قسم کی بھی غلطی ہوئی تو اس کا ذمہ دار کاریگر ہوگا۔";
lines[683]="        title={isUrdu ? 'ری سیٹ کی تصدیق' : 'Reset Confirmation'}";
lines[684]="        message={isUrdu ? 'کیا آپ واقعی تمام ناپ صاف کرنا چاہتے ہیں؟' : 'Are you sure you want to clear all measurements?'}";
lines[685]="        confirmText={isUrdu ? 'ری سیٹ' : 'Reset'}";
fs.writeFileSync('src/components/forms/CustomerMeasurementForm.tsx', lines.join('\n'));
